I add some useful and powerful function (like search to select on listbox, and clear all selects menu, and fix some bug)
hernandp/MessageCrackerWizard pull request #6
Opened 2024-08-20 17:56 UTC by HHsomeHand

1. fix 'menu -> view -> window Transparency' menu item cheked bugs

2. add menu item 'menu -> Edit -> Search listbox... ctrl + s' to search string from listbox [powerful]

3. add menu item 'menu -> Edit -> Clear All Selects' to clear all the selects

2024-08-20 18:10 UTC, HHsomeHand commented
vs2022 auto convert " Spanish (Spain, International Sort) " to "西班牙语(西班牙，国际风格) " in the .rc files because I use Chinese lanuage setting in vs2022. I didn't change it manually and didn't found the problem when i pull requeset....

2024-08-21 15:47 UTC, hernandp commented on MessageCrackWiz.rc
> +// ��������(�����������ʷ��) resources
Use international/English text, or add Chinese resources separately.

2024-08-21 15:47 UTC, hernandp commented on MessageCrackWiz.rc
> +// ��������(����͢) resources
Use international/English text, or add Chinese resources separately.

2024-08-21 15:47 UTC, hernandp commented on MessageCrackWiz.rc
> +#endif    // ��������(�����������ʷ��) resources
Use international/English text, or add Chinese resources separately.

2024-08-21 15:47 UTC, hernandp commented on MessageCrackWiz.rc
> +#endif    // ��������(����͢) resources
Use international/English text, or add Chinese resources separately.

2024-08-21 15:49 UTC, hernandp commented on MessageCrackWiz.vcxproj
> +    <WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion>
Do not change default build tools.
New platforms must be added separately, or we must migrate to other build system such as CMake.

2024-08-21 15:51 UTC, hernandp commented on MsgCrackWizard.cpp
> +        // ����ʹ��wcsstr���������ַ���
Use English/international text.

2024-08-21 15:51 UTC, hernandp commented on resource.h
> +// Microsoft Visual C++ ���ɵİ����ļ���
Same.

2024-08-22 02:34 UTC, hernandp commented on MessageCrackWiz.rc
> +        MENUITEM "Clear All Selects",           ID_EDIT_CLEARALLSELECTS
proper spelling would be 'Clear selection"  , use a shortcut key with the '&' prefix.

2024-08-22 02:35 UTC, hernandp commented on MsgCrackWizard.cpp
> +    WCHAR strItemText[512] = { 0 };
do not use magic numbers,  specify some constant like MAX_ITEM_TEXT

2024-08-22 02:36 UTC, hernandp commented on stdafx.h
> +#include <commdlg.h>
Do we need commdlg.h?

2024-08-22 02:37 UTC, hernandp requested changes
Please address the comments and do the proper fixes.

2024-08-22 11:06 UTC, HHsomeHand commented on stdafx.h
> +#include <commdlg.h>
yes,  we need it to show FindText Common Dialog

2024-08-22 11:13 UTC, HHsomeHand commented
In the latest commit, these issues are addressed

2024-08-22 14:47 UTC, hernandp commented
thanks @HHsomeHand  I will check them later

2024-09-17 14:45 UTC, hernandp commented
thanks for the modifications, I will merge them and review versioning in master. 

sorry for the late response, I was very busy.

2024-09-17 14:45 UTC, merged